### PR TITLE
Install icons and .desktop files

### PR DESCRIPTION
**Pull request by Mailaender**
adhering to the https://freedesktop.org/wiki/Standards/menu-spec/

### CODE REVIEW

**Comment by christopho** [comment]
Hi @Mailaender,
Thanks for your contributions. Note that the default branch of solarus is dev, not master. The master branch only points to releases.

**Comment by christopho** [comment]
@Mailaender you should be able to change the base branch of the pull request: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by christopho** [comment]
Merged manually into dev

**Comment by Mailaender** [comment]
Thanks and sorry for the mess. See the patch in action: https://build.opensuse.org/request/show/452105

**Pull request closed without merging**
